
type Query {
   allSession: [Session!]
   sessionByCode(code: String!): Session
}

mutation CreateLobby($code: String!, $rounds: [Round!]!, $deck: [Card!]! ,$players: [Player!]! ,$gameSate: String!, $dateCreated: String) {
     createSession(data: {code: $code, rounds: $rounds, deck: $deck, players :$players, gameState :$gameState, dateCreated : $dateCreated} ) {
         code
     }
}


type Session {
   code: String!
   rounds: [Round!]! @relation
   deck: [Card!]! @relation
   players: [Player!]! @relation
   gameState: String!
   dateCreated: String
}

type Card {
    id: Int!
    owner: String
    discarded: Boolean
    roundSubmitted: Int
    session: Session!
}

type Round {
    counter: Int
    storyTeller: String
    story: String
    storyTellerCard: Card
    votes: [Vote!]! @relation
    session: Session!
}

type Player {
    name: String!
    identifier: String!
    score: Int
    connected: Boolean
    id: String
    session: Session!
}

type Vote { 
    player: String!
    card: Int!
    round: Round!
}

