apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: cat ~/.docker/config.json | base64
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Secret
metadata:
  name: service-account-credential
type: Opaque
data:
  sa_json: <cat ../Secret/firestore.json | base64>